/* GENERATED by tools/gen-schema-c.mjs from static/wild/tweaks-schema.js — do not edit. */
#pragma once
#include <stdbool.h>
#include <stddef.h>

enum gt_type { GT_RANGE, GT_TOGGLE, GT_COLOR, GT_SELECT, GT_TEXT };

struct gt_item {
	const char *key;      /* JSON path in the page's tweaks object, e.g. "rings.style" */
	const char *setting;  /* obs_data key, e.g. "gt_rings_style" */
	enum gt_type type;
	double min, max, step, def_num;
	const char *def_str;
	bool def_bool;
	bool int_options;     /* GT_SELECT: options are ints */
	const char *options;  /* GT_SELECT: "a|b|c" */
	const char *labels;   /* GT_SELECT: display labels "x|y|z" (may be empty) */
	const char *label;
	const char *note;
	const char *group;    /* group title */
	int group_index;
	const char *looks;    /* engine family filter, "" = all */
	const char *placeholder;
	bool live;            /* page applies it without reload */
};

static const struct gt_item GT_ITEMS[] = {
	{ "channel", "gt_channel", GT_TEXT, 0, 0, 0, 0, "", false, false, "", "", "Triode check-in link", "paste your check-in page link, or just your channel name. \"\" = alderoshactual", "Connection", 0, "", "https://checkin.triodeofficial.com/YourName", false },
	{ "nameSize", "gt_nameSize", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Viewer name size", "1.0 = normal, 1.5 = 50% bigger, 0.8 = smaller", "Names", 1, "", "", true },
	{ "streamerNameSize", "gt_streamerNameSize", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Your name size", "your own name", "Names", 1, "", "", true },
	{ "pinWidth", "gt_pinWidth", GT_RANGE, 0.5, 8, 0.1, 1, "", false, false, "", "", "Needle thickness", "2.0 = twice as thick", "Pins", 2, "", "", true },
	{ "pinSize", "gt_pinSize", GT_RANGE, 0.5, 5, 0.05, 1, "", false, false, "", "", "Pin head size", "the dot on top", "Pins", 2, "", "", true },
	{ "pinColor", "gt_pinColor", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Viewer pin colour", "e.g. \"#ff3d81\" or \"hotpink\". \"\" = the look's own colour", "Pins", 2, "", "", true },
	{ "streamerColor", "gt_streamerColor", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Your pin colour", "\"\" = the look's own colour", "Pins", 2, "", "", true },
	{ "rings.style", "gt_rings_style", GT_SELECT, 0, 0, 0, 0, "waves", false, false, "waves|pulse|radar|halo|off", "", "Pattern", "waves (expanding rings) | pulse (one breathing ring) | radar (sweeping beam) | halo (soft glow) | off", "Rings under your pin", 3, "", "", true },
	{ "rings.count", "gt_rings_count", GT_RANGE, 1, 6, 1, 3, "", false, false, "", "", "Ring count", "for the waves style", "Rings under your pin", 3, "", "", true },
	{ "rings.speed", "gt_rings_speed", GT_RANGE, 0.25, 3, 0.05, 1, "", false, false, "", "", "Speed", "2.0 = twice as fast", "Rings under your pin", 3, "", "", true },
	{ "rings.size", "gt_rings_size", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Size", "overall size", "Rings under your pin", 3, "", "", true },
	{ "rings.color", "gt_rings_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Colour", "\"\" = same as your pin", "Rings under your pin", 3, "", "", true },
	{ "hurricane.size", "gt_hurricane_size", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Size", "1.5 = wider", "Hurricane", 4, "wind", "", true },
	{ "hurricane.strength", "gt_hurricane_strength", GT_RANGE, 0, 2, 0.05, 1, "", false, false, "", "", "Strength", "how hard it spins and pulls. 0 = off", "Hurricane", 4, "wind", "", true },
	{ "hurricane.color", "gt_hurricane_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Colour", "\"\" = the look's own colour (gold in most)", "Hurricane", 4, "wind", "", true },
	{ "land.color", "gt_land_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Continent colour", "e.g. \"#f3ecdc\" (cream) or \"#101820\" (near black). \"\" = the look's own", "Land", 5, "", "", true },
	{ "land.edge", "gt_land_edge", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Coastline colour", "\"\" = the look's own", "Land", 5, "", "", true },
	{ "ocean.on", "gt_ocean_on", GT_TOGGLE, 0, 0, 0, 0, "", false, false, "", "", "Show ocean current", "a sparse drift over the sea, against the land wind", "Ocean current", 6, "wind", "", false },
	{ "ocean.speed", "gt_ocean_speed", GT_RANGE, -2, 2, 0.1, 1, "", false, false, "", "", "Speed", "1.0 = against the land. -1.0 = with the land instead", "Ocean current", 6, "wind", "", false },
	{ "ocean.density", "gt_ocean_density", GT_RANGE, 0.25, 3, 0.05, 1, "", false, false, "", "", "Density", "1.0 = sparse, 2.0 = twice as many", "Ocean current", 6, "wind", "", false },
	{ "ocean.size", "gt_ocean_size", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Particle size", "", "Ocean current", 6, "wind", "", false },
	{ "ocean.alpha", "gt_ocean_alpha", GT_RANGE, 0.25, 3, 0.05, 1, "", false, false, "", "", "Brightness", "1.0 = faint, 2.0 = stronger", "Ocean current", 6, "wind", "", false },
	{ "ocean.color", "gt_ocean_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Colour", "\"\" = pale blue", "Ocean current", 6, "wind", "", true },
	{ "invert", "gt_invert", GT_SELECT, 0, 0, 0, 0, "", false, true, "0|1|2", "off|swap light/dark, keep colours|full negative", "Invert", "0 = off · 1 = swap light and dark but keep colours · 2 = full negative, colours flip too", "Colours", 7, "", "", true },
};
static const size_t GT_COUNT = sizeof(GT_ITEMS) / sizeof(GT_ITEMS[0]);
static const int GT_GROUP_COUNT = 8;
