/* GENERATED by tools/gen-schema-c.mjs from static/wild/tweaks-schema.js — do not edit. */
#pragma once
#include <stdbool.h>
#include <stddef.h>

enum gt_type { GT_RANGE, GT_TOGGLE, GT_COLOR, GT_SELECT, GT_TEXT };

struct gt_item {
	const char *key;      /* JSON path in the page's tweaks object, e.g. "rings.style" */
	const char *setting;  /* obs_data key, e.g. "gt_rings_style" */
	enum gt_type type;
	double min, max, step, def_num;
	const char *def_str;
	bool def_bool;
	bool int_options;     /* GT_SELECT: options are ints */
	const char *options;  /* GT_SELECT: "a|b|c" */
	const char *labels;   /* GT_SELECT: display labels "x|y|z" (may be empty) */
	const char *label;
	const char *note;
	const char *group;    /* group title */
	int group_index;
	const char *looks;    /* engine family filter, "" = all */
	const char *placeholder;
	bool live;            /* page applies it without reload */
};

static const struct gt_item GT_ITEMS[] = {
	{ "channel", "gt_channel", GT_TEXT, 0, 0, 0, 0, "", false, false, "", "", "Triode check-in link", "paste your check-in page link, or just your channel name. \"\" = alderoshactual", "Connection", 0, "", "https://checkin.triodeofficial.com/YourName", false },
	{ "nameSize", "gt_nameSize", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Viewer name size", "1.0 = normal, 1.5 = 50% bigger, 0.8 = smaller", "Names", 1, "", "", true },
	{ "streamerNameSize", "gt_streamerNameSize", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Your name size", "your own name", "Names", 1, "", "", true },
	{ "nameHeight", "gt_nameHeight", GT_RANGE, 0, 3, 0.05, 1, "", false, false, "", "", "Name height above surface", "how far names float above the ground (the needle length). 1.0 = normal, 2.0 = twice as high, 0 = on the surface", "Names", 1, "", "", true },
	{ "pinWidth", "gt_pinWidth", GT_RANGE, 0.5, 8, 0.1, 1, "", false, false, "", "", "Needle thickness", "2.0 = twice as thick", "Pins", 2, "", "", true },
	{ "pinSize", "gt_pinSize", GT_RANGE, 0.5, 5, 0.05, 1, "", false, false, "", "", "Pin head size", "the dot on top", "Pins", 2, "", "", true },
	{ "pinColor", "gt_pinColor", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Viewer pin colour", "e.g. \"#ff3d81\" or \"hotpink\". \"\" = the look's own colour", "Pins", 2, "", "", true },
	{ "streamerColor", "gt_streamerColor", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Your pin colour", "\"\" = the look's own colour", "Pins", 2, "", "", true },
	{ "trail.style", "gt_trail_style", GT_SELECT, 0, 0, 0, 0, "comet", false, false, "none|comet|sparkle|smoke|ribbon|embers|electric|datastream", "", "Trail", "all stream behind the pin head as the globe turns: comet (soft glowing tail) · sparkle (twinkling stars) · smoke (billowing puffs) · ribbon (continuous fading streak) · embers (rising fire sparks) · electric (crackling arc) · datastream (glitch pixels / hex digits)", "Pin trails", 3, "", "", true },
	{ "trail.length", "gt_trail_length", GT_RANGE, 0.25, 3, 0.05, 1, "", false, false, "", "", "Length", "how far the tail reaches", "Pin trails", 3, "", "", true },
	{ "trail.amount", "gt_trail_amount", GT_RANGE, 0.25, 3, 0.05, 1, "", false, false, "", "", "Density", "how many particles", "Pin trails", 3, "", "", true },
	{ "trail.size", "gt_trail_size", GT_RANGE, 0.25, 3, 0.05, 1, "", false, false, "", "", "Size", "particle size", "Pin trails", 3, "", "", true },
	{ "trail.color", "gt_trail_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Colour", "\"\" = the pin's colour", "Pin trails", 3, "", "", true },
	{ "trail.streamer", "gt_trail_streamer", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Also on your pin", "the broadcaster's pin gets the trail too", "Pin trails", 3, "", "", true },
	{ "rings.style", "gt_rings_style", GT_SELECT, 0, 0, 0, 0, "waves", false, false, "waves|pulse|radar|halo|off", "", "Pattern", "waves (expanding rings) | pulse (one breathing ring) | radar (sweeping beam) | halo (soft glow) | off", "Rings under your pin", 4, "", "", true },
	{ "rings.count", "gt_rings_count", GT_RANGE, 1, 6, 1, 3, "", false, false, "", "", "Ring count", "for the waves style", "Rings under your pin", 4, "", "", true },
	{ "rings.speed", "gt_rings_speed", GT_RANGE, 0.25, 3, 0.05, 1, "", false, false, "", "", "Speed", "2.0 = twice as fast", "Rings under your pin", 4, "", "", true },
	{ "rings.size", "gt_rings_size", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Size", "overall size", "Rings under your pin", 4, "", "", true },
	{ "rings.color", "gt_rings_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Colour", "\"\" = same as your pin", "Rings under your pin", 4, "", "", true },
	{ "hurricane.size", "gt_hurricane_size", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Size", "1.5 = wider", "Hurricane", 5, "wind", "", true },
	{ "hurricane.strength", "gt_hurricane_strength", GT_RANGE, 0, 2, 0.05, 1, "", false, false, "", "", "Strength", "how hard it spins and pulls. 0 = off", "Hurricane", 5, "wind", "", true },
	{ "hurricane.color", "gt_hurricane_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Colour", "\"\" = the look's own colour (gold in most)", "Hurricane", 5, "wind", "", true },
	{ "tubes.width", "gt_tubes_width", GT_RANGE, 0.3, 4, 0.05, 1, "", false, false, "", "", "Tube thickness", "2.0 = twice as thick", "Light tubes", 6, "tubes", "", true },
	{ "tubes.height", "gt_tubes_height", GT_RANGE, 0, 3, 0.05, 1, "", false, false, "", "", "Arc height", "how high the tubes arc off the globe. 0 = hug the surface", "Light tubes", 6, "tubes", "", true },
	{ "tubes.pulseSpeed", "gt_tubes_pulseSpeed", GT_RANGE, 0, 4, 0.05, 1, "", false, false, "", "", "Pulse speed", "light travelling along the tubes. 0 = still", "Light tubes", 6, "tubes", "", true },
	{ "tubes.pulses", "gt_tubes_pulses", GT_RANGE, 0, 4, 0.05, 1, "", false, false, "", "", "Pulse count", "2.0 = twice as many pulses. 0 = none", "Light tubes", 6, "tubes", "", true },
	{ "tubes.glow", "gt_tubes_glow", GT_RANGE, 0, 3, 0.05, 1, "", false, false, "", "", "Glow", "bloom strength. 0 = no glow", "Light tubes", 6, "tubes", "", true },
	{ "tubes.drawSpeed", "gt_tubes_drawSpeed", GT_RANGE, 0.25, 4, 0.05, 1, "", false, false, "", "", "Draw speed", "how fast a new tube draws itself", "Light tubes", 6, "tubes", "", true },
	{ "tubes.color", "gt_tubes_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Tube colour", "\"\" = follows the pin colour / the look's own", "Light tubes", 6, "tubes", "", true },
	{ "clouds.amount", "gt_clouds_amount", GT_RANGE, 0, 2, 0.05, 1, "", false, false, "", "", "Cloud cover", "0 = clear skies, 2 = overcast", "Clouds", 7, "clouds", "", true },
	{ "clouds.speed", "gt_clouds_speed", GT_RANGE, 0, 4, 0.05, 1, "", false, false, "", "", "Cloud speed", "how fast the weather moves. 0 = frozen", "Clouds", 7, "clouds", "", true },
	{ "clouds.opacity", "gt_clouds_opacity", GT_RANGE, 0.1, 2, 0.05, 1, "", false, false, "", "", "Thickness", "how solid the clouds look", "Clouds", 7, "clouds", "", true },
	{ "clouds.height", "gt_clouds_height", GT_RANGE, 0, 3, 0.05, 1, "", false, false, "", "", "Cloud height", "how far the cloud shell floats above the land", "Clouds", 7, "clouds", "", true },
	{ "clouds.color", "gt_clouds_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Cloud colour", "\"\" = the look's own", "Clouds", 7, "clouds", "", true },
	{ "clouds.lightning", "gt_clouds_lightning", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Lightning", "lightning strikes on check-ins", "Clouds", 7, "clouds", "", true },
	{ "clouds.lightningColor", "gt_clouds_lightningColor", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Lightning colour", "\"\" = the look's own", "Clouds", 7, "clouds", "", true },
	{ "sketch.style", "gt_sketch_style", GT_SELECT, 0, 0, 0, 0, "ink", false, false, "ink|pencil|chalk", "", "Ink", "ink (crisp black on a paper halo) · pencil (soft grey graphite) · chalk (white chalk on a dark halo)", "Field Notebook", 8, "sketch", "", true },
	{ "sketch.boil", "gt_sketch_boil", GT_RANGE, 0, 24, 1, 10, "", false, false, "", "", "Line boil speed", "how many times a second the hand-drawn lines re-wobble (0 = still lines)", "Field Notebook", 8, "sketch", "", true },
	{ "sketch.wobble", "gt_sketch_wobble", GT_RANGE, 0, 4, 0.1, 1, "", false, false, "", "", "Wobble", "how shaky the hand is. 0 = ruler-straight", "Field Notebook", 8, "sketch", "", true },
	{ "sketch.hatch", "gt_sketch_hatch", GT_RANGE, 0.25, 4, 0.05, 1, "", false, false, "", "", "Hatch density", "how close the shading lines on land are", "Field Notebook", 8, "sketch", "", true },
	{ "sketch.hatchAngle", "gt_sketch_hatchAngle", GT_RANGE, 0, 180, 1, 45, "", false, false, "", "", "Hatch angle", "direction of the shading lines (degrees)", "Field Notebook", 8, "sketch", "", true },
	{ "sketch.stopMotion", "gt_sketch_stopMotion", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Stop-motion spin", "the globe turns in little steps like hand-drawn animation; off = smooth spin", "Field Notebook", 8, "sketch", "", true },
	{ "sketch.halo", "gt_sketch_halo", GT_RANGE, 0, 1, 0.05, 0.55, "", false, false, "", "", "Halo strength", "the paper-white glow under every line and name, for reading over busy video. 0 = none", "Field Notebook", 8, "sketch", "", true },
	{ "glass.palette", "gt_glass_palette", GT_SELECT, 0, 0, 0, 0, "jewel", false, false, "jewel|pastel|amber|mono", "", "Glass palette", "jewel (ruby, sapphire, emerald, gold) · pastel · amber (cathedral golds) · mono (smoky clear glass)", "Stained glass", 9, "glass", "", true },
	{ "glass.cells", "gt_glass_cells", GT_RANGE, 40, 400, 10, 200, "", false, false, "", "", "Pane count", "how many panes make up the land. More = smaller panes", "Stained glass", 9, "glass", "", true },
	{ "glass.leadWidth", "gt_glass_leadWidth", GT_RANGE, 0.3, 4, 0.05, 1, "", false, false, "", "", "Lead width", "thickness of the black lead lines and the coastline", "Stained glass", 9, "glass", "", true },
	{ "glass.mottle", "gt_glass_mottle", GT_RANGE, 0, 3, 0.05, 1, "", false, false, "", "", "Glass texture", "mottle, streaks and bubbles in the glass. 0 = smooth", "Stained glass", 9, "glass", "", true },
	{ "glass.glint", "gt_glass_glint", GT_RANGE, 0, 4, 0.05, 1, "", false, false, "", "", "Glint speed", "how fast the light sweeps across the panes. 0 = still", "Stained glass", 9, "glass", "", true },
	{ "glass.oceanLead", "gt_glass_oceanLead", GT_RANGE, 0, 3, 0.05, 1, "", false, false, "", "", "Sea lead lines", "the faint lead net over the sea (ocean style auto). 0 = none", "Stained glass", 9, "glass", "", true },
	{ "glass.frame", "gt_glass_frame", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Window frame", "a lead ring round the globe", "Stained glass", 9, "glass", "", true },
	{ "scope.phosphor", "gt_scope_phosphor", GT_SELECT, 0, 0, 0, 0, "green", false, false, "green|blue|amber", "P31 green|P7 blue-white|P3 amber", "Phosphor", "the screen's phosphor; Continent colour overrides it with any colour", "Vector scope", 10, "scope", "", true },
	{ "scope.persistence", "gt_scope_persistence", GT_RANGE, 0, 1, 0.05, 0.5, "", false, false, "", "", "Persistence", "how long beams afterglow: swoops, writing, the retrace tail. 0 = snappy, 1 = long glow", "Vector scope", 10, "scope", "", true },
	{ "scope.beam", "gt_scope_beam", GT_RANGE, 0.3, 4, 0.05, 1, "", false, false, "", "", "Beam width", "thickness of every beam line", "Vector scope", 10, "scope", "", true },
	{ "scope.glow", "gt_scope_glow", GT_RANGE, 0, 4, 0.05, 1, "", false, false, "", "", "Glow", "phosphor bloom around the lines. 0 = none", "Vector scope", 10, "scope", "", true },
	{ "scope.retrace", "gt_scope_retrace", GT_RANGE, 0, 4, 0.05, 1, "", false, false, "", "", "Retrace speed", "beams re-drawing the coastline. 0 = steady, no retrace", "Vector scope", 10, "scope", "", true },
	{ "scope.jitter", "gt_scope_jitter", GT_RANGE, 0, 4, 0.05, 1, "", false, false, "", "", "Beam jitter", "analog shimmer on the coastline. 0 = rock steady", "Vector scope", 10, "scope", "", true },
	{ "scope.graticule", "gt_scope_graticule", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Grid lines", "the dim latitude/longitude grid", "Vector scope", 10, "scope", "", true },
	{ "paper.layers", "gt_paper_layers", GT_RANGE, 2, 7, 1, 5, "", false, false, "", "", "Paper layers", "how many cut-paper sheets the continents are stacked from", "Paper", 11, "paper", "", true },
	{ "paper.palette", "gt_paper_palette", GT_SELECT, 0, 0, 0, 0, "pastel", false, false, "pastel|kraft|atlas|mono|neon", "", "Paper colours", "pastel (soft rainbow) · kraft (brown card) · atlas (relief-map greens) · mono (white card) · neon (bright card). Continent colour overrides it", "Paper", 11, "paper", "", true },
	{ "paper.spacing", "gt_paper_spacing", GT_RANGE, 0, 3, 0.05, 1, "", false, false, "", "", "Layer spacing", "gap between the sheets: more = deeper stack, longer shadows, more parallax. 0 = flat", "Paper", 11, "paper", "", true },
	{ "paper.shadow", "gt_paper_shadow", GT_RANGE, 0, 2, 0.05, 1, "", false, false, "", "", "Shadow strength", "drop shadow under each sheet and onto your video. 0 = none", "Paper", 11, "paper", "", true },
	{ "paper.softness", "gt_paper_softness", GT_RANGE, 0.2, 3, 0.05, 1, "", false, false, "", "", "Shadow softness", "1.0 = soft, 0.3 = crisp, 3.0 = very blurry", "Paper", 11, "paper", "", true },
	{ "paper.tissue", "gt_paper_tissue", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Tissue-paper sea", "translucent blue tissue strips along the coasts (ocean style auto). Off = the swell pattern instead", "Paper", 11, "paper", "", true },
	{ "paper.flag", "gt_paper_flag", GT_SELECT, 0, 0, 0, 0, "banner", false, false, "banner|plain", "", "Name style", "banner (names on a paper ribbon) · plain (classic outlined names)", "Paper", 11, "paper", "", true },
	{ "dither.pixel", "gt_dither_pixel", GT_RANGE, 1, 4, 1, 2, "", false, false, "", "", "Pixel size", "screen pixels per dither pixel. 2 = crisp, 3–4 = chunky retro", "1-Bit", 12, "dither", "", true },
	{ "dither.inks", "gt_dither_inks", GT_SELECT, 0, 0, 0, 0, "bone", false, false, "bone|paper|phosphor|amber|gameboy|blueprint|riso|ice", "", "Ink pair", "the two inks (light / dark). Continent colour and Coastline colour override them", "1-Bit", 12, "dither", "", true },
	{ "dither.pattern", "gt_dither_pattern", GT_SELECT, 0, 0, 0, 0, "bayer8", false, false, "bayer4|bayer8|halftone|riso", "", "Dither", "bayer4 (coarse grid) · bayer8 (fine grid) · halftone (45° dot screen) · riso (halftone with the dark ink printed off-register)", "1-Bit", 12, "dither", "", true },
	{ "dither.contrast", "gt_dither_contrast", GT_RANGE, 0.3, 3, 0.05, 1, "", false, false, "", "", "Contrast", "how hard the light falls off into the shadow side", "1-Bit", 12, "dither", "", true },
	{ "dither.hatch", "gt_dither_hatch", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Engraved hatching", "latitude lines that thicken into the shadow. Off = plain dither", "1-Bit", 12, "dither", "", true },
	{ "dither.graticule", "gt_dither_graticule", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Graticule", "dotted 30° latitude/longitude lines over the sea", "1-Bit", 12, "dither", "", true },
	{ "dither.dial", "gt_dither_dial", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Pocket-watch dial", "the ticking watch dial around your pin (uses the ring colour/size/speed)", "1-Bit", 12, "dither", "", true },
	{ "land.color", "gt_land_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Continent colour", "e.g. \"#f3ecdc\" (cream) or \"#101820\" (near black). \"\" = the look's own", "Land", 13, "", "", true },
	{ "land.edge", "gt_land_edge", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Coastline colour", "\"\" = the look's own", "Land", 13, "", "", true },
	{ "ocean.on", "gt_ocean_on", GT_TOGGLE, 0, 0, 0, 0, "", true, false, "", "", "Animate the ocean", "a faint moving pattern over the sea; the sea itself stays see-through", "Ocean", 14, "", "", true },
	{ "ocean.style", "gt_ocean_style", GT_SELECT, 0, 0, 0, 0, "auto", false, false, "auto|swell|current|glint|dots", "", "Ocean style", "auto (the look's own) · swell (drifting wave lines) · current (flowing streaks) · glint (twinkling sparkles) · dots (pulsing dot grid)", "Ocean", 14, "", "", true },
	{ "ocean.speed", "gt_ocean_speed", GT_RANGE, -2, 2, 0.1, 1, "", false, false, "", "", "Speed", "1.0 = normal, -1.0 = the other way, 0 = still", "Ocean", 14, "", "", true },
	{ "ocean.density", "gt_ocean_density", GT_RANGE, 0.25, 3, 0.05, 1, "", false, false, "", "", "Density", "1.0 = sparse, 2.0 = twice as busy", "Ocean", 14, "", "", true },
	{ "ocean.size", "gt_ocean_size", GT_RANGE, 0.5, 3, 0.05, 1, "", false, false, "", "", "Size", "line / particle size", "Ocean", 14, "", "", true },
	{ "ocean.alpha", "gt_ocean_alpha", GT_RANGE, 0.25, 3, 0.05, 1, "", false, false, "", "", "Brightness", "1.0 = faint, 2.0 = stronger", "Ocean", 14, "", "", true },
	{ "ocean.color", "gt_ocean_color", GT_COLOR, 0, 0, 0, 0, "", false, false, "", "", "Colour", "\"\" = the look's own ocean colour", "Ocean", 14, "", "", true },
	{ "invert", "gt_invert", GT_SELECT, 0, 0, 0, 0, "", false, true, "0|1|2", "off|swap light/dark, keep colours|full negative", "Invert", "0 = off · 1 = swap light and dark but keep colours · 2 = full negative, colours flip too", "Colours", 15, "", "", true },
};
static const size_t GT_COUNT = sizeof(GT_ITEMS) / sizeof(GT_ITEMS[0]);
static const int GT_GROUP_COUNT = 16;
